name = "lutz-pfannenschmidt-website"
compatibility_date = "2026-02-25"

[assets]
directory = "./dist"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "lutz-pfannenschmidt.de"
custom_domain = true